### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hpanago** [hpanago/rigrep#1]
Write a documentation.md to explain in an easy way this repo's code.

**Comment by schedutron** [comment]
Let me do this.

**Comment by schedutron** [comment]
Can you just summarise in a line or two about what this code is really about?

**Comment by hpanago** [comment]
If I remember correctly, this started as a project to play around with reverse indexing, and seeing if we could make rigrep faster than grep. We had achieved this in some very rare, "lab"- kind environments.

**Comment by schedutron** [comment]
Alright, I'll start documentation based on that ASAP!

**Comment by hpanago** [comment]
Sounds perfect! Can't wait :)

**Comment by schedutron** [comment]
Also, I tested out your code, and although it gives the correct output, the output's untidy in the form of a Python list. I would also like to increase output readability. What's your say on this?

**Comment by hpanago** [comment]
What you say is true, the output is rather ugly. 

Of course I would accept a prettier form.

**Comment by schedutron** [comment]
See my work in #3 and let me know your thoughts. Furthermore, it's very costly to load the entire .index file into memory for lookups. Can we be more efficient than that? What about using a traditional database (I know, that sounds like an overkill)? Let me know what you think.

Again, thanks for letting me work on this interesting project!

**Comment by schedutron** [comment]
We should also add a repository mascot.

**Comment by hpanago** [comment]
Mascot? 

Saw #3, nice work, merged it.

Database, I think would indeed be an overkill. Since I would like this code to get faster, although sounds hard, maybe we could try and load things to memory (ram, cache) smarter? 

It's late and I am pitching stupid ideas. Have you tried it with a large .index?

**Comment by schedutron** [comment]
I've tried a large `.index`. The bottleneck is the loading (unpickling) of the dictionaries. That takes too much time. Once it's loaded, the lookup is quite fast. But the problem is that the dictionaries are loaded into memory every time we execute `rigrep.py`. We need to fix that.

And by mascot I mean a cool logo of some sort. Will make `README` look even better.

**Comment by hpanago** [comment]
Cool. We will continue this issue in #4. 
About the mascot, I have no designing skills whatsoever :P 
If you are really into it, open an issue, maybe we will find someone who likes drawing.
