### ISSUE TITLE
Add a repository mascot/logo

### ISSUE THREAD

**Issue by schedutron** [hpanago/rigrep#5]

**Comment by hpanago** [comment]
Ahem.. we are not Google. I can not accept that logo, I am sorry.

**Comment by schedutron** [comment]
@hpanago Alright! I thought that would suit the search functionality of this repo. So what theme should I consider?

**Comment by hpanago** [comment]
Maybe a simple, ascii art for start?

**Comment by mbruckert** [comment]
How about this:

![rigrep](https://user-images.githubusercontent.com/18492311/31855876-fa9558d2-b681-11e7-82e2-2fdb2005de85.png)
