### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by mattjegan** [hpanago/rigrep#6]
Python2 is end-of-life in 2020 and hence if you'd like the project to continue to live on into the distant future, supporting python3 would be advantageous. I would suggest making the code backwards compatible so we can support both py2 and py3 users 😄  Btw, thanks for the tool.

**Comment by hpanago** [comment]
Thanks for liking the tool :)

And you are very much correct, backwards compatibility should be achieved, especially now that there is not so much code to refactor.

However, my time is limited, so this will take some time.

Are you in any case willing to help with that or provide some general guidelines towards it?

Thanks.

**Comment by mattjegan** [comment]
Yeah no worries, working on it now.

**Comment by schedutron** [comment]
@mattjegan I think the `2to3` tool is going to help a lot here.
